### ISSUE TITLE
Filtering valuesets by "Draft" status returns error

### ISSUE THREAD

**Issue by braydengramse** [HealthCatalyst/Fabric.Terminology#109]
API call: GET http://clinicalprb-terminology.hqcatalyst.local/v0.7/valuesets?%24status=Draft
Error Message: Failed to find ValueSetCode collection for every ValueSetBackingItem (ValueSetDescription)

**Comment by braydengramse** [comment]
I haven't been able to reproduce this on green monster only on dev0002.

**Comment by rustyswayne** [comment]
dev0002 was the issue - did not have correct permissions.
