### ISSUE TITLE
Use the latest version of Code System Code when creating custom value sets

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#14]
In order to insert value set codes into the new SQL table `[ClientTerm].[ValueSetCodeBASE]` we will be required to include a few fields that we have not exposed in the API.

- BindingID (required)
- BindingNM (required)
- LastLoadDTS (required)
- VersionDSC (required)
- SourceDSC (required)

While there may an argument to include the VersionDSC and SourceDSC in the API, these fields really only have meaning as meta information in the context of EDW and Terminology databases (specific) so there seems to be little is no reason to require the apps to pass this information back and forth.  Further, the binding fields are deactivated with respect to the SAM after created via the SAM Designer ... so essential the SAM will ignore the table and they are meaningless.

Since we cannot create codes through the API (and they are essentially read only) it makes sense that the non binding values are copied from the codes referenced so we will need to populate them before saving.  

I'm proposing that we agree to codes based on the `CodeCD` and `CodeSystemCD`  and use the "latest version".  _Note: At the moment the Terminology team only has a `LatestVersionFLG` field on the value sets (not the code system codes) but it can be done by additional constraints in the query._

This will make it much easier for consumers of the API to create custom value sets as essentially all they would need is those two fields to represent the codes. The alternative could wind up being a fairly large JSON object to POST back (given that some value sets have thousands of codes).  

Really need feedback on this one!

**Comment by rustyswayne** [comment]
@corytak @j2jensen With respect to the binding information, I'm going to incorporate a variant of the Null Object Pattern and simply assume that everything has the same binding.

         /// <summary>
    /// Provides HC specific binding information in instances where field information is required
    /// but no binding was used to create the record.
    /// </summary>
    internal class EmptySamdBinding
    {
        public string BindingID => "0000";

        public string BindingNM => "ValueSetCodeClient";

        public DateTime GetLastLoadDTS(DateTime? lastLoad = null)
        {
            return lastLoad ?? DateTime.UtcNow;
        }
    }

I ran the idea by Clint on the Terminology team and he thought it was a sound approach to that aspect of the issue.

Note: We are going to have a similar issue with the actual value set object that contains the codes - but I believe I that is handled correctly with the `IValueSetMeta` interface introduced in the initial prototype.  The plan is to allow for consumers (e.g. MBL / PRB) to include a configuration file in their applications that can be used to populate the values for the `ValueSetApiModel` as I'm guessing they will be pretty constant per application.
    
    public class ValueSetMetaApiModel
    {
        public string AuthoringSourceDescription { get; set; }

        public string PurposeDescription { get; set; }

        public string SourceDescription { get; set; }

        public string VersionDescription { get; set; }
    }

**Comment by j2jensen** [comment]
@rustyswayne I haven't had time to completely grok this, but it sounds like you've got a pretty firm grasp on the problem and nothing stands out to me as dangerous.

I am a little confused by the purpose of `GetLastLoadDTS()` in your code sample, and I'd suggest that using `DateTime.UtcNow` directly is a code smell. Seems like maybe a factory could leverage an `IClock` to produce the time and pass it into the object's constructor. But, again, I haven't been able to follow the Terminology API development as closely as the PRB work, so I might not know what I'm talking about. 😄

**Comment by rustyswayne** [comment]
@j2jensen The idea for the `GetLastLoadDTS()` is to actually pass the LastLoadDTS value from the actual code value ... the fallback is for testing when I'm generating test codes.

**Comment by corytak** [comment]
@rustyswayne Looks good to me.
