### ISSUE TITLE
Should Update Custom ValueSet be implemented?

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#15]
At the moment we are only implementing the ability to create a custom ValueSet.  Once created, the `IValueSet` becomes essentially read only at this point.  

We will be implementing a DELETE.

**Comment by mikebuck** [comment]
Yes we would eventually want to do Update as well but we could get by with Create and Delete for awhile.

**Comment by j2jensen** [comment]
Both UPDATE and DELETE present the possibility of breaking any measures, registries, etc., which depend on the ValueSet. For example, if the hospital is tracking how many patients meet certain criteria as part of their regulatory reporting, they may not want someone to be able to change how that's measured (maybe accidentally) by changing a ValueSet that the calculation happens to depend on. 

My initial impression is that ValueSets need to be immutable. Or maybe we could create a locked-down, published state that's easier to share across different apps and cannot be changed, but allow changes to be made to ValueSets that are in a kind of draft mode?

**Comment by mikebuck** [comment]
Good point, we should investigate Archive and Update functions rather than a Pure Delete/Update. That way the older versions are immutable once deployed or out of draft mode like you suggest. We can do some more design thinking around this.

**Comment by corytak** [comment]
The flip side of this coin is there may be instances where the user would want the changes they make in a value set (perhaps a code was included erroneously) to cascade to multiple measures/rulesets where it is used. Having to update each one individually with a new value set that has the fix may prove tedious. I'm mostly on board with immutable value sets, but would like to think through how to solve this problem in our apps as well.

**Comment by mikebuck** [comment]
That is an important feature, I think the cascade can happen if our apps can handle the experience of upgrading to the newest version of a particular valueset. We shouldn’t have to update each one individually I agree as that is not only tedious but error-prone.

Mike

**Comment by mikebuck** [comment]
Sounds good to me. Mike
