### ISSUE TITLE
Sorting value sets by "Last Modified" or "Authority" leads to unpredictable ordering

### ISSUE THREAD

**Issue by petermcclanahan** [HealthCatalyst/Fabric.Terminology#167]
As pictured below, you can see that sorting by "Authority" leads to unpredictable ordering. The same is true for the "Last Modified" column. The second image below shows that the ordering is indeed being sent to the TerminologyService. 

![image](https://user-images.githubusercontent.com/20196383/46314476-ee0ebc00-c587-11e8-8c5b-77e47acab6a9.png)

![image](https://user-images.githubusercontent.com/20196383/46314568-2f9f6700-c588-11e8-933d-23f9f77d81f5.png)

**Comment by rustyswayne** [comment]
Fixed with #168
