### ISSUE TITLE
Add ability to query for distinct list of Code Systems

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#18]

**Comment by rustyswayne** [comment]
@corytak How are you guys doing this right now?  I'm hoping for a better solution than a select distinct from a code set or hard coding.

**Comment by j2jensen** [comment]
@rustyswayne I'm not sure exactly what you're asking about here, but you might want to look at `ValueSetSummaryRepository.SelectActivePublicByCriteria()` in PRB.

**Comment by corytak** [comment]
@rustyswayne we run a stored procedure to import the data from terminology. Part of that process is normalization and we query from a new table called CodeSystemBASE.

**Comment by rustyswayne** [comment]
@j2jensen That's basically what I think should be native in the API - so we're on the same page.  @corytak I'll have a look for that table - name looks promising.  What I hope to accomplish it to provide a lookup which would most likely be queried from a consumer (in our case the SDK library on deck next) which values would be cached after queried.  This would be used to provide the drop down values for toggling between code systems when searching for codes to populate new value sets.

Many thanks guys!
