### ISSUE TITLE
Create a list of irrelevant ClientTerm fields

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#21]
The Terminology Team asked us to go through the [ClientTerm].[ValueSetDescriptionBASE] and [ClientTerm].[ValueSetCodeBASE] and come up with the list of fields to be removed from our perspective.

**Comment by rustyswayne** [comment]
@ClintLing, @j2jensen @corytak 

### [ClientTerm].[ValueSetDescriptionBASE]

**Remove**
- LastLoadDTS
- ValueSetID
- VersionDSC
- DefinitionDSC
- Source DSC
- PurposeDSC
- TypeDSC
- RevisionDTS
- CreatedByNM

### [ClientTerm].[ValueSetCodeBASE]

**Remove**
- LastLoadDTS
- ValueSetID
- ValueSetOID
- ValueSetNM
- VersionDSC
- RevisionDTS
- SourceDSC

**Comment by j2jensen** [comment]
LastLoadDTS is put there by the SAM ETL process. If we get rid of it, we should also get rid of BindingNM and BindingID. If we can't get rid of those, then we probably can't get rid of LastLoadDTS either.

**Comment by j2jensen** [comment]
I think we still need to keep ValueSetID on ValueSetDescription, just to have something for ValueSetVersion to have its foreign key on, right?

**Comment by rustyswayne** [comment]
@j2jensen  I thought I heard Cessily and/or Clint mention that the actual ID was ValueSetOId which comes from the published sets.  In the db ValueSetID and ValueSetOId are (at least as far as I've seen) the same.  Do you think there is a reason to have both ValueSetId and ValueSEtOId?

**Comment by ClintLing** [comment]
We don't have an OID for everything.  In the case of VSAC the OID is the ID, but there are often cases where there is no OID and so the item only has a valuesetID.  I would like to think about that a little more and discuss it with Cessily.  The question I need to ask her is how important is it for the average customer to know that the id is an OID or not, or to have an OID for a value set if it is available.  I think for the client authoring it doesn't seem like a field that would get populated very often by the client, unless they were cloning an existing value set.  So if we got rid of one of these it would have to be the OID.  I will let you know.
