### ISSUE TITLE
When ClientTerm SAM is regenerated, how do we prevent existing ClientTerm data from being dropped?

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#43]
@ClintLing I know we've discussed this in the past, but I could not remember the answer and was hoping you could jot down your thoughts here so that everyone has a chance to get their concerns addressed.  

The question was posed to me yesterday be @j2jensen who was inquiring what would happen to the data in the ClientTerm tables when the SAM was regenerated (specifically when columns are added or removed based on version) ...

**Comment by ClintLing** [comment]
Our only prevention of deletion of the data that after we install we inactivate the bindings in the SAM so that if anyone runs the SAM again, it won’t overwrite the data.  I don’t have any other means to prevent that.

Clint
