### ISSUE TITLE
Conversion failed when converting from a character string to uniqueidentifier

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Terminology#47]
Endpoints are failing with this exception:

> Conversion failed when converting from a character string to uniqueidentifier

 Noticed in the views that the Guids have the datatype of varchar(255).

**Comment by rustyswayne** [comment]
@corytak What views are you seeing the Guid as a varchar(255)?   Can you confirm your looking at the correct schema?

**Comment by corytak** [comment]
It's working now. I was looking at the Terminology DB rather than the Shared DB.
