### ISSUE TITLE
Ability to Sort List of Value Sets by attributes

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Terminology#52]
Should be able to sort list of value sets by attribute (name, identifier, isCustom)

**Comment by rustyswayne** [comment]
@corytak I don't see the value in sorting by identifier or the IsCustom properties - albeit adding an endpoint to query for only custom value sets does make sense to me.  Identifier is a GUID - did you mean ValueSetReferenceId ...

**Comment by corytak** [comment]
@rustyswayne here's an example of the columns that are currently sortable:
![image](https://user-images.githubusercontent.com/9749465/31466146-63546418-ae93-11e7-867f-f39ae9b6aa4f.png)

So OID, Name, Version, Source, and Code Count would be ideal

**Comment by corytak** [comment]
Here's a more recent screenshot:
![image](https://user-images.githubusercontent.com/9749465/35364186-fc3f435c-012a-11e8-95a4-83deba334830.png)
