### ISSUE TITLE
Ability to move forward and back in value set list

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Terminology#55]
Given a list the user has already sorted and filtered on the first screen, allow the user to move forward and backward on the list from the summary view:

![image](https://user-images.githubusercontent.com/9749465/31445557-81aed0d4-ae5b-11e7-987d-36e06d0633ec.png)

We handled this in MBL by passing in the sortBy column, sortOrder, searchTerm and take/skip values when we ask for an individual value set. Then we're able to determine what the next and previous value set ids are. This solution, however, was somewhat ugly and it may be wise to think more deeply about different approaches.

**Comment by rustyswayne** [comment]
@corytak Aside from the additional sort fields, isn't this already possible with the paging values returned?

**Comment by corytak** [comment]
Closing this as I got it to work with client side code only.
