### ISSUE TITLE
GET /valuesets/{ValueSetGuid} URL length only allows around 7 comma-separated values

### ISSUE THREAD

**Issue by braydengramse** [HealthCatalyst/Fabric.Terminology#56]
While testing in Postman and Chrome, I've noticed that if you have more than about 7 CSVs it will return   400 Bad Request - Invalid URL. I'm assuming it has to do with the URL length but I guess I could be wrong. It's possible that someone will have more than 7 value sets associated with a rule set or measure. Should this endpoint be modified to allow more than 7 CSVs?

**Comment by rustyswayne** [comment]
Great check Brayden! I've confirmed that (when run locally) the request fails after 7 GUIDs - no where near the ~2000 char limit.  Maybe an issue with Nancy and parameter length?? 

In any event, given that in this endpoint you can also include CodeSystemGuids in the query string the URL can become something not easily managed outside of code quite quickly.   I think we should refactor this method to only expect a single ValueSetGuid and provide a new POST `/valuesets/mulitple` enpoint which will accept an array of values in a JSON body.  

Related #54, we could follow this pattern in the forthcoming `/codes/` API.

@corytak Do you have any opinion?

**Comment by corytak** [comment]
@rustyswayne We do have a use case where we need to compare two value sets together, but if we push that to `/valuesets/multiple`  that would be fine with me as long as we have some way to pull down multiple simultaneously. 

Would also love some endpoint that does a diff server side, but it can be done client side as well.

**Comment by rustyswayne** [comment]
Does diff simply compare code differences or is it more sophisticated?

**Comment by corytak** [comment]
Given two or more value set identifiers, we return a list of codes that are present in all of the value sets and then enumerate the value set ids to which the code belongs. Here's an example comparing two value sets with 1 code each:
```
  "codes": [
    {
      "codeDescription": "Warfarin",
      "codeSystemName": "RXNORM",
      "codeSystemVersion": "2016-01",
      "codeValue": "11289",
      "valueSetCount": 2,
      "valueSetList": [
        3,
        4
      ]
    },
    {
      "codeDescription": "fondaparinux",
      "codeSystemName": "RXNORM",
      "codeSystemVersion": "2016-01",
      "codeValue": "321208",
      "valueSetCount": 1,
      "valueSetList": [
        4
      ]
    }
  ],
  "resultNumber": 2
}
```

**Comment by rustyswayne** [comment]
@corytak Thanks!   I'm going to refactor the /valuesets/{valueSetGuid} endpoint  to only ever expect a single Id (Guid) and then add the POST /valuesets/multiple/ endpoint as discussed.
