### ISSUE TITLE
CodeSystems are listed without published codes

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#57]
@ClintLing I think there will be a need to filter the code systems that actually have codes available, especially if you consider the use case where a drop down or multi-select list is rendered to a user with the intent of selecting code systems to search for codes to be added to a custom value set.  

It would also be nice to know how many codes are published per code system.  What do you think about adding a column to the [Terminology].[CodeSystem] view to include the `CodeCount` which could also be used to determine if any codes are available ... e.g. CodeCount > 0

@corytak @j2jensen

**Comment by ClintLing** [comment]
I like that idea.  It would take some of the pressure off of our internal discussion about what to do about large coding systems we don't necessarily want to bring through.  I will work on bringing that field through the release process.

**Comment by corytak** [comment]
@rustyswayne in the filter bar for the list of value sets some desired filters are source, and version, would we want to update the code system filter to only show relevant values. E.g. the filtered versions end up being just for the year 2016 and there happened to be no RXNorm codes during that time frame then we may want to not show  (or disable) that code system.
