### ISSUE TITLE
Implementing the FHIR Specification

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#75]
@j2jensen @mikebuck @corytak @clintling

I have been going over my notes from the code review last week and one of the discussion points that popped up in the code review last week was to refactor the API to return JSON conforming (at least loosely) to the FHIR spec. _https://www.hl7.org/fhir/valueset.html_ This makes sense from a purely OSS standpoint and perhaps the long term vision but as I started planning for the revision, it quickly became evident that we as a team should have a discussion weighing the immediate implications.

Thus far, I have been more concerned with finding common requirements between internal Health Catalyst teams  (primarily PB and MBL) with the objective of creating a mechanism for sharing statically published and client created content between various HC applications.  As a result, the current implementation of the API has been developed to directly provide for the _**specific functional requirements dictated by these HC applications**_ with little to no priority given to considering _**potential usage**_ by other API consumers.

To be discussed:

PB and MBL application's internally use very similar models to what is currently returned from the API due to the fact that, at present, they are querying directly from the SQL schema.  
**Does it make sense for the API to map results from this current point of commonality to FHIR?**
Thinking from the perspective of a PB team developer, I'm pretty confident we would essentially wind up having to map the API response model right back so that we did not have a bunch of breaking changes in the PR UI.  

Likewise, it occurs to me that changing the underlying SQL Schema to more closely approximate the FHIR spec would be even more problematic as it would likely create a bunch of breaking changes without the buffer of the API (e.g. no fallback) and likely introduce versioning/compatibility issues between installations that are arguably unnecessary.

We should also comment and/or document the foreseeable benefits of implementing the FHIR specification as at this point I'm struggling to reconcile the "bang for the buck".  

Assuming the directive will be to implement the specification, I'd also like to at least consider doing so via a series of different endpoints - e.g. `/1.0/fhir/valuesets` or something to that effect.  

Pros

- We can still focus on internal team requirements (limit breaking changes)

Cons

- Additional maintenance requirements with respect to versioning
- Adds to time required when adding new features, fixing issues, and testing

**Comment by corytak** [comment]
From the MBL perspective, we would also have to spend time mapping the FHIR model to the models that are already used in our UI. I would lean towards limiting the breaking changes with what's working now and either kicking these changes down the road or treating the development FHIR endpoints as a separate endeavor.
