### ISSUE TITLE
Query ValueSet by UniqueID (GUID)

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#8]
If the `ValueSetUniqueID` property gets added to the API models, it makes sense to add the ability to retrieve a ValueSet by the ID.

**Comment by rustyswayne** [comment]
@j2jensen @corytak Any preferences what the endpoint should like like for this?

**Comment by corytak** [comment]
Ideally we would be able to do something as simple as a GET `/api/valuesets/{:id}`. I don't have any experience with this format and GUIDs, however. If that is problematic it may make more sense to do this similar to the way you've done the `/api/valuesets/find` endpoint where we pass something in the body.

**Comment by j2jensen** [comment]
I agree with Cory--if it's an exact search based on the primary identifier, it should be `/api/valuesets/{id}`. Guids shouldn't present any problems this way, since they don't have slashes in them. Web API's default model binding should be smart enough to parse them from a variety of different formats (with or without dashes, e.g.).

**Comment by rustyswayne** [comment]
At the moment the /v1.0/valuesets/{id} endpoint is being used for the ValueSetId field queries.  We could add a query string parameter to provide the instruction that we want to use ValueSetOId or the new ValueSetUniqueId field.

Something like:

/v1.0/valuesets/{id}?$idfield=ValueSetOId 

Where valid $idfield values would be:

- ValueSetId
- ValueSetOId
- ValueSetUniqueId

Default (no param) would be ValueSetId as it is now.

**Comment by rustyswayne** [comment]
@j2jensen @corytak Food for thought - in the ClientTerm tables (custom ValueSet) the Terminology table has made the ValueSetUniqueId field the primary key so there may be a valid reason to make that field the default.  That being said, I know it would be a breaking change for the PRB app so we'd wind up having to do something in the SDK to limit the integration headache.

**Comment by corytak** [comment]
ValueSetUniqueId would be preferable for MBL. However, if it needs to be more flexible, we can work around that too.

**Comment by j2jensen** [comment]
I feel ambiguous about using the unique ID as the primary identifier. On the one hand GUIDs don't work super well for indexing and joining in the database. On the other hand, it feels weird having more than one identifier for a given type of object.

I wouldn't use the `/v1.0/valuesets/{id}?$idfield=ValueSetOId`-style syntax, though. I'd rather establish one type of ID as the one that `/v1.0/valuesets/{id}` queries, and all other values should be queried using standard query parameters: `/v1.0/valuesets?valueSetOid={oid}`. The client can be responsible for applying `.Single()` logic on the results.

**Comment by rustyswayne** [comment]
I've added this as a discussion point to bring to the meeting with the Terminology team, but am leaning toward using the `ValueSetUniqueID`  as it makes things consistent with the Value Sets stored in ClientTerm schema (primary key on that table) and @corytak comment above that it would be preferable to the MBL team.  

I think this also addresses @j2jensen comment:
> I'd rather establish one type of ID as the one that /v1.0/valuesets/{id} queries, and all other values should be queried using standard query parameters: /v1.0/valuesets?valueSetOid={oid}. The client can be responsible for applying .Single() logic on the results.

e.g. We could return ALL versions of a Value Set (not just the latest) when the ValueSetID or ValueSetOID is passed in the query string and allow the client to be responsible for sorting out which version they want.

**Comment by j2jensen** [comment]
That last point is very interesting. I was under the impression that `ValueSetOID`, `ValueSetID`, and `ValueSetUniqueID` would change for a new Version, but it appears that Green Monster has hundreds of value sets with the same `ValueSetOID` and `ValueSetID`, but with different `VersionDSC`s. In this case, `ValueSetUniqueID` is the only single value that's uniquely identifying a given version of the ValueSet. You might want to check with Clint that this is how it's supposed to be.

I don't know if there's a reliable way to know which Version is "latest", since they're only identified by their Version Description.

Finally, I'm realizing that since ValueSetID is both non-unique and a string, it would be a poor choice as a primary key (or a foreign key target from ValueSetCodes). So is there any reason for its existence?

**Comment by rustyswayne** [comment]
@j2jensen I think you and I are just get getting caught up with some of the issues @corytak and the MBL team have had with the `ValueSetID`  and `ValueSetOId` fields for some time.  I was lucky enough to sit in on a conversation with them before I started so I knew that they would not be unique ... but I did write in the assumption to always return the latest version even knowing that it would create a legacy issue when new versions of published value sets were pushed.  Luckily I can confirm the the Terminology team is managing the ValueSetUniqueID per version and that field is indeed unique.  

With respect to the FK to value set codes, I agree there could be an issue - albeit we are using the massive compounded key so I think we're doing things as intended (in the PRB app).  I believe MBL introduced their own keys for these as well  ...

With the respect custom value sets, we're going to be fine since the values are copied and the UniqueId is used as the FK in that situation.  Related will be this issue: https://github.com/HealthCatalyst/Fabric.Terminology/issues/14

**Comment by rustyswayne** [comment]
@mikebuck @clintling I apologize, I should have included you on this thread - especially as it relates to @j2jensen query

> Finally, I'm realizing that since ValueSetID is both non-unique and a string, it would be a poor choice as a primary key (or a foreign key target from ValueSetCodes). So is there any reason for its existence?

**Comment by ClintLing** [comment]
It may be redundant from a local authoring perspective.  However, the ValueSetID represents the ID given by the source and is often useful in locating the value set needed for a given measure or other purpose.  It isn't always the same as the OID and OID won't always be populated.  From an authoring perspective at a client, I imagine the Unique ID fits the bill.  If we are going to combine the items authored locally and the value sets HC distributes from other sources in the same view then we will have to put up with the redundancy.  I think the ValueSetId will continue to be a useful field to find value sets, so I am not ready to drop it - but from a local authoring perspective it probably doesn't need to be part of the key.  For distribution of external value sets it is part of the process.
