### ISSUE TITLE
500 when searching by draft status in search

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Terminology#85]
Currently receiving the following error when searching by `Draft` status:
```
{
	"code": "InternalServerError",
	"message": "Failed to find ValueSetCodeCounts collection for every ValueSetBackingItem (ValueSetDescription)",
	"target": "ValueSetApiModel",
	"details": null,
	"innererror": null
}
```

For full context here's the body being posted to the `/valuesets/search` endpoint:
```
{
	"codeSystemGuids": [],
	"pagerSettings": {
		"currentPage": 1,
		"itemsPerPage": 12
	},
	"statusCode": "Draft",
	"summary": true,
	"term": ""
}
```

When statusCode is swapped out with `Archived` or `Active` there are no errors.

**Comment by rustyswayne** [comment]
This had to do with a couple of records in the ClientTerm.ValueSetDescriptionBASE table that did not have associated records in the ClientTerm.ValueSetCodeCountBASE table.  I've cleared the tables which resolved the issue but we need to watch for this to happen again in case it's possible for the API to put add records to ClientTerm.ValueSetDescriptionBASE without also updating ClientTerm.ValueSetCodeCountBASE.
