### ISSUE TITLE
Best way to validate unique Value Set Name (500 error when Value Set is same name)

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Terminology#92]
When attempting to make a copy, I'm defaulting the name of the value set to be `'Copy of ' + name`. This works fine, but it's possible for name collisions to take place. Further, someone may unwittingly name a value set the same name as another value set and not get an error until saved. Some potential solutions:

- UI to run a query with the entered value set name against `/valuesets/search` and see if any names exactly match

- auto increment the name on the backend. e.g. first copy is `Copy of ValueSet` and the next copy is `Copy of ValueSet1`. 

The user is immediately routed to the edit screen when a copy is made so this could be a possibility.

**Comment by rustyswayne** [comment]
I sort of leaning toward the UI querying to validate the name.  In my opinion, the UI should present a modal  asking the user to enter the new name (and asynchronously validate the name's uniqueness) prior to making the copy request as I think it's reasonable to assume the user will end up renaming the value set anyway in which case the name is still going to have to be unique.

Incrementing a number on the end or even  appending random characters would be easy, but we'd wind up with the same renaming issues.

**Comment by corytak** [comment]
I think what I'll plan on for now is adding the time stamp when copied from the list view and then add validation in the edit view.
